### ISSUE TITLE
Vnoun or NOUN?

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#17]
@amir-zeldes

I am not sure yet when we analyze צורת מקור as VERBs VerbForm=Vnoun and when as NOUNs. Is it related to the ADP?
For example, in the sentence 
 לאחר שובה לישראל החלה לעבוד כחוקרת

Since it is a צורת מקור I wonder if שוב should be considered as a predicate, and analyzed in this way:
`advcl`(hexela, shoov)
`mark`(shoov, leaxar)
`nsubj`(shoov, h)
`obl`(shoov, Israel)
Or as a regular nominal `obl`, and analyzed in this way:
`obl`(hexela, shoov)
`case`(shoov, leaxar)
`nmod:poss`(shoov, h)
`nmod`(shoov, Israel)

**Comment by amir-zeldes** [comment]
These should be analyzed as regular nouns IMO, just like verbal nouns in Slavic etc. The only exception is the unusual contemporaneous adverbial clause construction with "be-lexto" etc., which HTB has analyzed as VERBal. Note that the above can be substituted with any NOUN, suggesting it is also a NOUN:

  * leaxar shuva le-yisrael / leaxar masa'-a le-nepal (masa' is a regular noun, not a masdar)

But the HTB analysis of be-lexto suggests there is something special with the following:

  * be-lexto la-bank hu ra'a tsipor

Syntactically, we can also say someone "ra'a tsipor be-masa'-o", but I think the idea is that you don't get the special adverbial clause semantics. I admit it's a very subtle judgment though, and if it weren't for HTB I'd be tempted to just treat all of these as NOUN to make life simpler...

**Comment by shirawigi** [comment]
@amir-zeldes  @Hilla-Merhav 

Would you say there's a difference between the analysis of the structure with צורת מקור and the "real" nominal structure, for example:
בספטמבר 1950 תיאר בקצרה העיתון 'דבר' את **היעלמו**.
vs.
בספטמבר 1950 תיאר בקצרה העיתון 'דבר' את **היעלמותו**.

Or that if we agree now that צורות מקור are NOUNs (in this context) then they should be analyzed exactly the same way?

What would you say the lemma of these nominal צורות מקור should be?
is it the same as for the verbal form or is it a different one?
Also, how do we assign it the other features - gender and number?

**Comment by amir-zeldes** [comment]
I think the accusative case is a good argument for these being plain nouns, as is the parallelism with other synonyms. If we tag them as VERB, the I think taking 3rd person singular past is normal and expected (for the advcl cases with be- etc.), but for cases we annotate as NOUN I would probably reconstruct a hypothetical היעלם as the lemma, no? I think the default gender for these things is Masc and Sing, but maybe there are some which are feminine as well (such as חזרתו, next to the proper masdar חוזרו, which I think is Masc)
