### ISSUE TITLE
Predication anaphoric ZOT (זאת)

### ISSUE THREAD

**Issue by strasss** [IAHLT/UD_Hebrew#23]
@amir-zeldes

Consider the following sentences:

1. ב-25 באפריל 2002 התייצבה אלון, בליווי עורך דינה, במשרדי מחלק ההונאה של מחוז תל אביב והתוודתה על מעילת הענק שביצעה בבנק, **זאת** בעקבות חקירה של בנק ישראל בבנק למסחר שנכנסה ליומה השלישי.”

2.  נותנת בידי הממונה סמכות לבטל היתר שניתן, ו**זאת** מבלי לתת טעם לדבר

In a discussion in slack two alternative analyses were suggested:

a. זאת would be the subject of clauses whose predicates are בעקבות חקירה and מבלי לתת in 1 and 2 respectively, i.e. it would be governed by חקירה and לתת through the deprel `nsubj`.

b. זאת would be the head of an NP, governing חקירה and לתת through the deprels  `nmod` and `advcl` (or `acl`?) in 1 and 2 respectively.

Needless to say the correct analysis doesn't have to be either of these two and can actually be something else entirely :)

**Comment by amir-zeldes** [comment]
I think it's a., which is even more 'normal-looking' since Hebrew allows a PP predicate without a copula anyway. In other words, this is like an English copula predicate:

"and this (is) without/following..."

**Comment by strasss** [comment]
Thanks, @amir-zeldes !
And how would  the ZOT clause be connected to the main clause? 
I guess in sentence 2 it could just be  `conj` from **לבטל** to **לתת** as there's as a CCONJ there. 
But what about sentence 1? `parataxis` from **התייצבה** to **חקירה**? It feels a bit too flat of a relation, so to speak, but I wonder if there's anything else we can use

**Comment by IsraelLand** [comment]
Alternatively, `dep` has also been discussed, but that can be "too semantic" (then again `parataxis` might be "too flat", so...).

**Comment by amir-zeldes** [comment]
No, I think parataxis is right for the other one - it literally means two syntactic structures are standing next to each other without any overt syntactic connection (even if pragmatically/stylistically there is some connection, but that is true of anaphora and other phenomena as well)

**Comment by IsraelLand** [comment]
Thank you!
