### ISSUE TITLE
'amur/nitan/efshar haya' - frozen-form modals and their deprels in a broader context

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#24]
Hi @amir-zeldes,
We previously discussed such cases as:

`ניתן יהיה לשנות`

as "nitan", not inflected by itself, but by "haya/"yihiye" in an `aux` relation, tagged structurally as `aspect=prog`.

I was wondering what's the `aux` structure in the broader context - 
1. is it aux(nitan, yihiye) then another aux(leshanot, nitan)? This is more accurate IMHO because 'nitan yihiye' can stand on its own, but it may be problematic validation-wise?
2. or it may be that all are related by `aux` to 'leshanot' ('fountain shape').

(Any guideline mentions are before we made the decision about these cases, so we might need to change some)

Thank you!

**Comment by IsraelLand** [comment]
Omer turned my attention to the fact that 'nitan' is irrelevant here, 
What I am asking really is about these specific mostly-modal tokens, which behave very much the same -
יכול, צריך, חייב, מוכרח, מסוגל
אינו, הינו, היה, אין, יש
מוכן, רשאי, זכאי, צפוי
עשוי, עתיד, אמור, עלול

Most cannot usually be inflected non-periphrastically, and they get the deprel `aux` in cases like
`הוא צריך היה ללכת`

Thank you!

**Comment by amir-zeldes** [comment]
The answer to this is actually determined by UD guidelines globally and isn't pretty: AUX cannot have dependents, so all AUX will be individually attached to the main lexeme, regardless of internal structure. This is a bit ugly in English to in cases like:

I was being sarcastic
I will have been tricked
It's to be continued

In all of these, the last word dominates all AUX and marks (yes, even "continued" dominates the "to" which properly belongs to "be"). This is a hard guideline enforced by the validator, no exceptions...

**Comment by IsraelLand** [comment]
Great, that answered it completely. Thanks!
