### ISSUE TITLE
The constructions `ka + adjective\participle` or `be\ba + adjective\participle`

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#28]
@amir-zeldes

As opposed to unsegmented expressions like כמובן and כנראה and במיוחד, we do segment כ+ראוי and כ+רגיל and ב+רגיל and analyze it compositionally. Usually, when it is governed by a predicate (as it is in most cases) we analyze it like this:
`obl`(_**predicate**_,ragil)
`case`(ragil,ka)

We have recently noticed similar constructions: כ+בינוני or ב+בינוני:
כמתבקש, כמתחייב, כמשתמע, כאמור
In my batch now I also have – במשתמע
(הסעיף אוסר **במשתמע** גם ייעוץ ללא ייצוג)

My first question is – do we want to analyze the `כ/ב + adjective` and the `כ/ב + participle` in the same way?
If we do, I wonder how we should do it. In case we want to keep the `obl` analysis and apply it to the participles – what should be the participles' POS?
In case we want to analyze the participles as VERBs, should we stop `obl`ing these consructions? Should we analyze them as `advcl` instead?

**Comment by amir-zeldes** [comment]
It's exactly as you say: if we keep them as VERB, then they have to be advcl. I think I actually prefer that, it's a bit like saying in English:

  * כמשתמע = as is being implied -> advcl+VERB

OR:

  * כמשתמע = as the implied (one) -> obl + NOUN

Even for an adjectival reading, you can tag ADJ and use advcl on the analysis that it's a reduced adjectival predicate clause. So overall I think advcl is not wrong here, and lets you keep verbal properties in tact, such as passive voice (for ka-amur etc.)

**Comment by Hilla-Merhav** [comment]
@amir-zeldes

Yes, I understand – the fact that both ADJs and VERBs can be governed by an `advcl` deprel is indeed an advantage of the `advcl` solution. So, from now, should we analyze כראוי and כרגיל as `advcl`s?

`advcl`(**_predicate_**,ragil)
`mark`(ragil,ka) 

`advcl`(**_predicate_**,rauy)
`mark`(rauy,ka)

If we do – I can also add it to the "amending the HTB" list (this is not a lot of work – If I'm not mistaken, only 3 occurrences of each). 
I hope I don't miss any more ADJs that can go with this structure.

In case the consistency between ADJs and participles is not that important, we can also go for a solution of `obl`ing the ADJs and `advcl`ing the participles – what do you recommend?

**Comment by amir-zeldes** [comment]
I don't feel strongly about it. The original UD HTB does use nmod/obl for the regular adjectives, so that's a small argument in favor of it, and you need to tag VERB or ADJ anyway, so you have to decide which ones are adjectives in any case.

**Comment by Hilla-Merhav** [comment]
> In case the consistency between ADJs and participles is not that important, we can also go for a solution of `obl`ing the ADJs and `advcl`ing the participles – what do you recommend?

@amir-zeldes
So is my last suggestion the best solution? Should we tag **_ka/be+participle_** as `advcl` (participle's POS=VERB, ka/be's POS=SCONJ), and **_ka/be+regular adjective_** (like רגיל) as `obl` (POS=ADJ)?

**Comment by amir-zeldes** [comment]
Sure, I would be OK with that, and it's that path of least resistance since HTB won't need changing for these cases.

**Comment by Hilla-Merhav** [comment]
@amir-zeldes Thanks! Should I add כ and ב to the SCONJ closed classes for that purpose?

**Comment by amir-zeldes** [comment]
Yes, I suppose they would have to be possible then!

**Comment by Hilla-Merhav** [comment]
@amir-zeldes Thanks, I added them. I also added `מ` for נמנע **מ**לעשות, הניא אותו **מ**לעשות if it's OK :)
