### ISSUE TITLE
ADV in nismax position

### ISSUE THREAD

**Issue by Hilla-Merhav** [IAHLT/UD_Hebrew#35]
@amir-zeldes

How do you think we should analyze expressions like **למחרת החקירה**?

Usually as far as I know `compound` is deprel only NOUNs (and sometimes maybe ADJs) govern through, but למחרת is an ADV.

The HTB solution – in its one and only occurrence – is `fixed`ing it. But since every NOUN that refers to any event can occur in this environment, this solution doesn't look applicable to me.

Also, I think this question connects to the לבד+ו issue ([#32](https://github.com/IAHLT/UD_Hebrew/issues/32)) – this is a general question about the connection between a governor ADV and a dependent NOUN/PRON.

**Comment by amir-zeldes** [comment]
TBH I think it should be segmented, so you get back to le+maxarat, and then everything is OK. Can we treat it as the construct state form of maxar in this case? We can still decide separately if we like "lemaxarat" when it appears by itself as an ADV (this is like how "ha-yom" is one token for "today" and two for "the day")

**Comment by Hilla-Merhav** [comment]
@amir-zeldes 
Sounds good. 
In Even Shoshan I see that מחר is both adverb and masculine noun, but its nismax form is **מְחַר־**, and מחרת is a separate lexical item – also both adverb and noun, but a feminine noun, so I suggest the lemma of מחרת would be מחרת and we assign to it the feature Gender=Fem, is it OK?

**Comment by amir-zeldes** [comment]
OK!
