### ISSUE TITLE
Hebrew years

### ISSUE THREAD

**Issue by shirawigi** [IAHLT/UD_Hebrew#52]
Hi @amir-zeldes,

Sometimes we come across a year written according to the Hebrew calendar, e.g. תרפ"ט, תשנ"ט, and also ה' תרפ"ט or התש"ח.
We discussed between us several ways to annotate these years.
When the ה is missing, there’s no problem, and we all agree it should be just NUM, like any other case of gematria. This is also compatible with the guidelines (the google doc version).
When the ה is present though, we couldn’t agree on a certain way:
1.	In the guidelines it says to treat the ה as an affix like that: compound:affix(trm, h), when the tokens are separated.
in my opinion, this is somewhat problematic for several reasons: sometimes the ה is written as a separate token from the rest of the year, but sometimes it doesn’t, which will create a situation where the same year has two structures; ה is not truly an affix, just like 1 is not an affix in 1980; compound suggest a hierarchy between the two tokens, which is not true in the case of Hebrew years;
2.	Another suggestion was to always segment the year as a single token – even when the ה is separated from the rest of the year it should be unified and tagged NUM.
3.	If we wish to stick to the original text, we could use ‘flat’ between ה and the rest of the year when it is segmented into 2 tokens, and tag both parts as NUM.

What do you think?
Thanks!

**Comment by amir-zeldes** [comment]
In the spirit of 2 there is an even more tailor-made solution, especially if you state that spelled together should be the standard - you can use `goeswith`: https://universaldependencies.org/u/dep/goeswith.html

**Comment by shirawigi** [comment]
@amir-zeldes 
Thanks!
I like your suggestion of using `goeswith`. And I suppose both tokens remain NUM, right?

**Comment by amir-zeldes** [comment]
Yes! Closing unless there are other open issues on this
