### ISSUE TITLE
heemid pney yashen

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#69]
Hi @amir-zeldes

I've been wondering about
העמיד פני ישן
Pretended to be asleep
Somewhat literally - stood up a face (of) sleeping.3rd.prs - put on a face (of sleeping)

Which I feel somewhat of a secondary predication between "heemid" and "yashen".
Thing is, if I attach xcomp(heemid,yashen), I cannot deprel compound(pnei,yashen), which has an overt construct form.

Alternatively this might be obj(heemid, pney), then a compound, but I don't really feel that he's really מעמיד את הפנים in an actual obj position between the first two.
This might be out of scope, too semantic, and thus obj indeed.
We can do obl:npmod as well, if it isn't a true obj.

So the way I see it -
1. xcomp(heemid,yashen), compound(pnei,yashen) - X this is impossible (though intuitively the most fitting)
2. xcomp(heemid,pnei), compound(pnei,yashen) - Possible, but the 2nd predication doen't seem to really relate to pnei
3. obj(heemid,pnei) , compound(pnei,yashen) - Not sure a true object, nor do we express the xcomp-iness (if there's even one)
4. obl:npmod(heemid,pnei) , compound(pnei,yashen) - this avoids the object issue, but perhaps it shouldn't

In addition, we might employ a different approach than compound, but I'm hesitant because of the overt smixut-compound,
and the question of yashen - adj or noun, much less important imo, still remains.

Thank you.

**Comment by amir-zeldes** [comment]
I see the issue. In English, the list of verbs taking secondary predicates is fairly limited, and probably my knee jerk response would be 3, the literal reading (basically, the tree is syntax, if you want semantics you need another annotation layer).

That said, if you really wanted to be nearer to the semantics, I think the solution would not be 1 or 2. The easiest way to do it IMO would be to treat 'he'emid pnei' as a fixed expression taking a secondary predicate, and then yashen as xcomp:

fixed(heemid, pnei)
xcomp(heemid, yashen)

That would make 'heemid panim' a kind of complex verb, which I think semantically is fairly true. But TBH I would not actually recommend this. I prefer predictable analyses, even if they are very robotic, to cool and avant garde ones that only make sense when you look at them. If you don't read the TB sentence by sentence, you won't see this insightful analysis, but a normal search for all compounds, or all transitive verbs or also quantitative evaluations would all be thrown off by such cases without anyone noticing. 

That's just one reason why semantic and MWE analyses on top of UD are really indispensible if you want to analyze everything in the text. Morphosyntactically, "pnei yashen" is pretty much a normal compound...

**Comment by IsraelLand** [comment]
Thank you. I see why adding another layer of complex verbs to Hebrew is not adviseable (I would count stuff like הולך ומתמעט or עומד\עתיד ללכת as more pressing, if anything, but even these don't really seem to warrant such a big addition, on top of regular old aux)

**Comment by amir-zeldes** [comment]
Yeah, it's really something for a semantics layer, or if that's too involved, then a minimal solution for something like this is MWE annotation, with or without WSD.
