### ISSUE TITLE
"covert" conditionals

### ISSUE THREAD

**Issue by IsraelLand** [IAHLT/UD_Hebrew#72]
Hi @amir-zeldes

המשרד הגיש בקשה לצו מניעה כנגד הסתדרות המורים בשישי בבוקר, ובלי פשרה בין הצדדים, הם צפויים להגיע לבית הדין לעבודה.

בלי פשרה בין הצדדים, הם צפויים להגיע לבית הדין לעבודה
[[without a compromise], they may end up in court]

I'm sure this has been disscussed before - I see a conditional here, and I wonder if I should just tag "what I see", which is the obvious obl, or rather, if I'm being honest to my mental reading, this is an advcl conditional.

It's not that they may end up, with no compromise in hand, at court - It's that [**if** they go] without a compromise, they'll be in court.

I'm aware of the difficulties of advcl in this environment, imo they aren't insurmountable, but first I'm interested to know if I even should read this much into the sentence to begin with.
(This is not semantic, really, more usage based, and I'm of the opinion that much of what we do involves exactly this discretion between readings - but in this case it really has a syntactic implication)

Thanks

**Comment by amir-zeldes** [comment]
I think it's still obl. Prepositions can have a variety of readings, and in this case I agree that "without" has a conditional reading (like 'unless'). But syntactically, I think it's the same PP modifier of the predicate. Part of the issue might be that in a proper constituent tree formalism, without UD-style lexicocentrism, the "without" PP might actually be a dependent of the modal ("without this, they might..."), but UD prohibits dependents of `aux`. If you say "the might arrive in court without a compromise", then i think it's clearer the "without" PP modifies the lexical predicate 'arrive'.

In any case, my reading of this situation would be that it's still a PP modifier, and the conditional meaning is maybe a different sense of the preposition "without".

**Comment by IsraelLand** [comment]
Yeah I see what you mean, not syntactically represented. Thanks!
